URL_COURIER_CREATION = 'https://qa-scooter.praktikum-services.ru/api/v1/courier'
URL_COURIER_LOGIN = 'https://qa-scooter.praktikum-services.ru/api/v1/courier/login'
URL_ORDER_CREATION = 'https://qa-scooter.praktikum-services.ru/api/v1/orders'
URL_ORDER_LIST = 'https://qa-scooter.praktikum-services.ru/api/v1/orders'
URL_COURIER_DELETE = 'https://qa-scooter.praktikum-services.ru//api/v1/courier/'
